image: mcr.microsoft.com/dotnet/sdk:latest

stages:
    - clean
    - build
    - test
    - publish
    - run
clean: 
    stage: clean
    script:
        - "dotnet clean"
build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/
test:
    stage: test
    script: 
        - "dotnet test"
publish:
    stage: publish
    script:
        - "dotnet publish"
    artifacts:
      paths:
        - bin/
run:
    stage: run
    script:
        - "dotnet run"
